export const loginButton: string = '//div[text()="Вход"]';
export const loginLink: string = 'a.auth-form__button_fb';
export const cartButton: string = 'a.auth-bar__item';
export const text: string = 'div.cart-form__title_condensed-additional';
export const searchInputField: string = 'fast-search__input';
export const frame: string = '//iframe[@class="modal-iframe"]';
export const searchImage: string = 'div[class="search__content-wrapper"]';
export const linkToTheProduct: string = '//span[text()="Триммеры"]';
export const checkText: string = 'js-schema-header_title';
export const searchLink: string = '//span[text()="Моторные масла"]';
export const searchButton: string = '//span[text()="Объявления"]';